#!/usr/bin/env perl
use strict;
use feature "say";
use FindBin '$Bin';
use lib $Bin.'/../lib';
use Tools;

my $path = Tools::git_root();

my ($appcode, $codepool, $namespace, $module) = $path =~ m{^(app/code)/(core|community|local)/(\w+)/(\w+)};

if (!$appcode || $appcode ne 'app/code') {
    die "not in app/code";
}

say "${namespace}_${module}";
say $codepool;
